module.exports = {
  users: [
  {"id":1,
  "username":"stormtrooper","name":"Terrence","avatar":"https://s-media-cache-ak0.pinimg.com/originals/60/b7/30/60b73041000047d4e8737d4eee9c5a08.png","email":"trooperlove@stormtrooper.com", "favorite food":"spaghetti", "firstDate": "I like doing something fun on the first date, like cooking, or going to a pod race."},
  {"id":2,
  "username":"snowtrooper","name":"Fred","avatar":"https://s-media-cache-ak0.pinimg.com/originals/dd/11/1f/dd111ff5042dc332fef3e297df41ea75.jpg","email":"stormlover@stormtrooper.com", "favorite food":"vanilla ice cream", "firstDate": "There's a little place on the death star that has the best ice cream.  I love to go there on my days off with someone special"},
  {"id":3,
  "username":"stormtrooper","name":"Barney","avatar":"https://d13yacurqjgara.cloudfront.net/users/458522/screenshots/2352857/star_wars___stormtrooper___dribbbler.jpg","email":"barney001@stormtrooper.com", "favorite food":"Chicken soup", "firstDate": "I like finding a quiet place on the death star where I can be alone, and just think about what I want to do with my life"},
  {"id":4,
  "username":"stormtrooper","name":"Dave","avatar":"http://plasmainfusion.com/Ep%20V%20ST%20Helmet.jpg","email":"barney001@stormtrooper.com", "favorite food":"Chicken soup", "firstDate": "I don't go on many dates.  I'm too busy fighting Jedi."},
  {"id":5,
  "username":"snowtrooper","name":"Greg","avatar":"https://trooperbay.com/media/catalog/product/cache/1/small_image/280x210/9df78eab33525d08d6e5fb8d27136e95/t/f/tfa_trooper_decal.jpg","email":"Greg-The-Invincible@stormtrooper.com", "favorite food":"Protien Shake", "firstDate": "I'm simple.  I prefer staying inside, and watching one of my favorite episodes of Star Trek"},
  {"id":6,
  "username":"snowtrooper","name":"Bruce","avatar":"http://www.thecollectorscantina.com/sites/default/files/sites/default/files/field/image/tfaproduct1.png","email":"whiteThunder@stormtrooper.com", "favorite food":"Cotton Candy", "firstDate": "I like cruising around in a tie fighter for some peace and quiet"},
  {"id":7,
  "username":"snowtrooper","name":"Tim","avatar":"http://vignette4.wikia.nocookie.net/clubpenguin/images/d/d4/Stormtrooper_Helm.png/revision/latest?cb=20130725140749","email":"Mean-Lean-Machine@stormtrooper.com", "favorite food":"Chocolate Milk", "firstDate": "Long walks on the beach, so I can feel the sand squish between my boots"},
  {"id":8,
  "username":"stormtrooper","name":"Bob","avatar":"http://vignette4.wikia.nocookie.net/swgames/images/8/8a/501helmet.jpg/revision/latest?cb=20110926153238","email":"hungry-for-love@stormtrooper.com", "favorite food":"Italian Sausages", "firstDate": "I like to look out of the window of the death star and imagine what life is like on all the little stars in the galaxy"},
  {"id":9,
  "username":"snowtrooper","name":"Jason","avatar":"https://s-media-cache-ak0.pinimg.com/originals/60/b7/30/60b73041000047d4e8737d4eee9c5a08.png","email":"Greg-The-Invincible@stormtrooper.com", "favorite food":"Mushrooms", "firstDate": "Watching the pod races on tatooine with someone special"},
  {"id":10,
  "username":"snowtrooper","name":"Chad","avatar":"http://2.bp.blogspot.com/-1NI8fH2h_IQ/UmMCz8YrXyI/AAAAAAAAA_E/22ad6CyZg8w/s1600/stormtrooperpumpkinstencil.jpg","email":"Tatooine-Lover@stormtrooper.com", "favorite food":"Fried Green Tomatoes", "firstDate": "My ideal first date is going to the cantina, listening to some good music, and having a few casual drinks"},
  {"id":11,
  "username":"snowtrooper","name":"Sam","avatar":"http://img06.deviantart.net/df8c/i/2008/217/7/9/storm_trooper_helm_by_guerrillasuit.jpg","email":"UnderArmor@stormtrooper.com", "favorite food":"Pizza", "firstDate": "Looking for droids"},
  {"id":12,
  "username":"stormtrooper","name":"Robert","avatar":"http://www.sothebys.com/content/dam/stb/lots/N09/N09014/121217RA_stormtrooper_helmet_027.jpg","email":"YummyLicious@stormtrooper.com", "favorite food":"Pop Tarts", "firstDate": "I like dressing up as a jedi, and pretending I'm in a light-sabre battle."}]}
